name: Shopper Agent Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'src/app/agents/shopperAgent_initializer.py'
      - 'src/prompts/ShopperAgentPrompt.txt'
  pull_request:
    branches:
      - main
    paths:
      - 'src/app/agents/shopperAgent_initializer.py'
      - 'src/prompts/ShopperAgentPrompt.txt'
  workflow_dispatch:

jobs:
  run-shopper-agent:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Set environment variables
        run: |
          echo "${{ secrets.ENV }}" >> $GITHUB_ENV

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Shopper Agent
        run: |
          python src/app/agents/shopperAgent_initializer.py
        env:
          ACR_LOGIN_SERVER: ${{ secrets. ACR_LOGIN_SERVER }}
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
          ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
          APPLICATIONINSIGHTS_CONNECTION_STRING: ${{ secrets.APPLICATIONINSIGHTS_CONNECTION_STRING }}
          AZURE_AI_AGENT_API_VERSION: ${{ secrets.AZURE_AI_AGENT_API_VERSION }}
          AZURE_AI_AGENT_ENDPOINT: ${{ secrets.AZURE_AI_AGENT_ENDPOINT }}
          AZURE_AI_AGENT_MODEL_DEPLOYMENT_NAME: ${{ secrets.AZURE_AI_AGENT_MODEL_DEPLOYMENT_NAME }}
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          AZURE_PROJECTS_ENDPOINT: ${{ secrets.AZURE_PROJECTS_ENDPOINT }}
          INDEX_NAME: ${{ secrets.INDEX_NAME }}
          SEARCH_ENDPOINT: ${{ secrets.SEARCH_ENDPOINT }}
          SEARCH_KEY: ${{ secrets.SEARCH_KEY }}

      - name: Azure Logout
        if: always()
        run: |
          az logout
        continue-on-error: true
